import {
  orgData, teamData, setTeamData, workOrders, setWorkOrders, portfolio, setPortfolio,
  ownerColors, countUnowned,
} from './state.js';
import {
  getOpsProfile, getCompanyName, _showActionToast,
  COMPANY_KEY, OPS_PROFILE_KEY, LAUNCH_CHECKLIST_KEY, applyCompanyName, applyOpsProfile,
  saveTeamData, saveWorkOrders, savePortfolio, saveToStorage, logAudit,
} from './storage.js';
import { escapeHtml, _slugify, getLeaseStatus, getDelinquencyStatus, formatCurrency } from './utils.js';
import { ROLE_TEMPLATES, buildDemoWorkspace } from './templates.js';

// Maintainer note:
// This module powers the top-of-dashboard Launch Plan and "Start Here" next
// step buttons. It reads live state from state.js, profile data from storage.js,
// and exposes handlers through app.js -> window for inline onclicks. If you
// rename exported functions here, update app.js Object.assign(window, ...) and
// any onclick strings generated by renderLaunchPlan().


const PROFILE_LABELS = {
  small: 'Under 100 doors',
  mid: '100-500 doors',
  large: '500+ doors',
  stability: 'Stabilize ownership',
  maintenance: 'Tighten maintenance flow',
  growth: 'Scale team capacity',
  compliance: 'Reduce compliance risk',
};

const FOCUS_BLUEPRINTS = {
  // Department ids must exist in config.json. Missing ids are filtered out at
  // render time, but that makes the recommended blueprint feel incomplete.
  stability: {
    title: 'Ownership Stabilization',
    summary: 'Get every recurring responsibility named, backed up, and visible before the week gets noisy.',
    departments: ['tenant-comms', 'maintenance', 'delinquency', 'owner-relations'],
  },
  maintenance: {
    title: 'Maintenance Command Center',
    summary: 'Stand up intake, vendor routing, emergency escalation, and closeout discipline from day one.',
    departments: ['maintenance', 'vendors', 'unit-turns', 'tenant-comms'],
  },
  growth: {
    title: 'Scalable Team Capacity',
    summary: 'Separate daily operating work from growth work so new doors do not bury the team.',
    departments: ['leasing', 'applications', 'move-ins', 'accounting'],
  },
  compliance: {
    title: 'Compliance-Safe Operations',
    summary: 'Make the highest-risk duties explicit, documented, and reviewed on a reliable cadence.',
    departments: ['compliance', 'delinquency', 'accounting', 'reporting'],
  },
};

const BASE_CHECKLIST = [
  {
    id: 'portfolio',
    label: 'Add the first managed property and vendor',
    detail: 'Record at least one property plus one reliable vendor so the operating map has real-world context.',
    metric: () => portfolio.properties.length > 0 && portfolio.tenants.length > 0 && portfolio.vendors.length > 0,
  },
  {
    id: 'owners',
    label: 'Assign every red UNOWNED responsibility',
    detail: 'Start with daily tenant, maintenance, rent, and owner communication work.',
    metric: () => countUnowned() === 0,
  },
  {
    id: 'critical-coverage',
    label: 'Cover the seven critical PM responsibility lanes',
    detail: 'Confirm leasing, rent collection, inspections, maintenance, compliance, renewals, and emergencies have named owners.',
    metric: () => getCriticalCoverageAreas().every(area => area.coveragePct >= 70),
  },
  {
    id: 'maintenance',
    label: 'Define maintenance intake and escalation',
    detail: 'Name who monitors the queue, who dispatches vendors, and who handles after-hours emergencies.',
    metric: () => hasAssignedDepartment('maintenance') && hasAnyWorkOrderSignal(),
  },
  {
    id: 'rent',
    label: 'Lock the rent collection routine',
    detail: 'Confirm who reviews delinquencies, sends notices, answers ledger questions, and escalates legal handoff.',
    metric: () => hasAssignedDepartment('delinquency') && hasAssignedDepartment('accounting'),
  },
  {
    id: 'vendors',
    label: 'Create the starter vendor bench',
    detail: 'Add at least one work order with a vendor or document the preferred vendor owner.',
    metric: () => workOrders.some(w => (w.vendor || '').trim()),
  },
  {
    id: 'owner-reporting',
    label: 'Set owner reporting expectations',
    detail: 'Pick the owner communication lead and define the weekly update rhythm.',
    metric: () => hasAssignedDepartment('owner-relations'),
  },
];

const FOCUS_CHECKLIST = {
  maintenance: [
    {
      id: 'maintenance-aging',
      label: 'Review open repair aging every morning',
      detail: 'Use Work Orders to keep submitted and in-progress jobs from going stale.',
      metric: () => workOrders.some(w => w.status !== 'completed'),
    },
  ],
  growth: [
    {
      id: 'leasing-capacity',
      label: 'Separate leasing growth work from operations work',
      detail: 'Make sure showings, applications, and move-ins have named owners before adding doors.',
      metric: () => hasAssignedDepartment('leasing') && hasAssignedDepartment('applications') && hasAssignedDepartment('move-ins'),
    },
  ],
  compliance: [
    {
      id: 'inspection-cadence',
      label: 'Document inspection and compliance cadence',
      detail: 'Assign inspections, notices, and recordkeeping before exceptions start piling up.',
      metric: () => hasAssignedDepartment('unit-turns') && hasAssignedDepartment('compliance'),
    },
  ],
  stability: [
    {
      id: 'backup-coverage',
      label: 'Check backup coverage for overloaded roles',
      detail: 'Use Team Manager to rebalance any person carrying a large share of the operating map.',
      metric: () => getOverloadedOwners().length === 0,
    },
  ],
};

const CRITICAL_COVERAGE_AREAS = [
  {
    id: 'leasing',
    label: 'Leasing',
    detail: 'Listings, showings, applications, and move-in handoff.',
    departments: ['leasing', 'applications', 'move-ins'],
  },
  {
    id: 'rent',
    label: 'Rent Collection',
    detail: 'Delinquencies, ledgers, notices, and payment follow-up.',
    departments: ['delinquency', 'accounting'],
  },
  {
    id: 'inspections',
    label: 'Inspections',
    detail: 'Move-ins, move-outs, turns, field visits, and condition reports.',
    departments: ['move-ins', 'move-outs', 'unit-turns', 'field-services'],
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    detail: 'Intake, triage, vendors, emergency dispatch, and closeout.',
    departments: ['maintenance', 'vendors'],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    detail: 'Fair housing, notices, insurance, records, and risk controls.',
    departments: ['compliance', 'reporting'],
  },
  {
    id: 'renewals',
    label: 'Renewals',
    detail: 'Rent increases, lease questions, move-outs, and owner alignment.',
    departments: ['tenant-comms', 'owner-relations', 'leasing'],
  },
  {
    id: 'emergencies',
    label: 'Emergencies',
    detail: 'After-hours repair response, access, vendors, and tenant updates.',
    departments: ['maintenance', 'vendors', 'field-services', 'tenant-comms'],
  },
];

const SEVEN_DAY_PLAN = [
  {
    day: 1,
    title: 'Build the source of truth',
    base: 'Add your first properties, units, tenants, owner/client context, and vendor bench.',
    focus: {
      stability: 'Keep the registry simple and complete before assigning more work.',
      maintenance: 'Prioritize emergency vendors and access notes for every property.',
      growth: 'Separate active doors from upcoming doors so growth work does not blur current operations.',
      compliance: 'Capture owner/client and tenant contact context cleanly for notices and recordkeeping.',
    },
    action: { label: 'Open Portfolio', onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))" },
  },
  {
    day: 2,
    title: 'Replace sample roles with real people',
    base: 'Add the team, choose department affinities, and confirm who should own each operating lane.',
    focus: {
      stability: 'Make sure no critical lane depends on one overloaded person.',
      maintenance: 'Name who watches intake, dispatches vendors, and follows up daily.',
      growth: 'Separate leasing capacity from daily operations capacity.',
      compliance: 'Name who owns notices, records, insurance, and compliance review.',
    },
    action: { label: 'Open Team', onclick: 'startTeamSetup()' },
  },
  {
    day: 3,
    title: 'Close ownership gaps',
    base: 'Work through UNOWNED tasks and assign the highest-risk responsibilities first.',
    focus: {
      stability: 'Start with tenant communication, rent collection, maintenance, and owner updates.',
      maintenance: 'Start with emergency response, work order triage, vendor dispatch, and access coordination.',
      growth: 'Start with showings, applications, move-ins, and owner onboarding.',
      compliance: 'Start with notices, inspections, fair housing controls, and reporting.',
    },
    action: { label: 'Show Gaps', onclick: 'showUnownedTasks()' },
  },
  {
    day: 4,
    title: 'Test maintenance intake',
    base: 'Create one realistic work order with property, tenant, vendor, assignee, cost, priority, due date, and notes.',
    focus: {
      stability: 'Use a routine tenant request to prove the daily workflow.',
      maintenance: 'Use a high-priority repair and walk it from submitted to scheduled.',
      growth: 'Use a move-in or make-ready issue so leasing handoff is visible.',
      compliance: 'Use a repair with documentation or owner approval risk.',
    },
    action: { label: 'Create Work Order', onclick: 'startWorkOrderSetup()' },
  },
  {
    day: 5,
    title: 'Review critical coverage',
    base: 'Check leasing, rent collection, inspections, maintenance, compliance, renewals, and emergencies.',
    focus: {
      stability: 'Confirm every critical lane is at least 70% covered.',
      maintenance: 'Confirm maintenance and emergencies have named primary and backup coverage.',
      growth: 'Confirm leasing, applications, and move-ins can absorb new doors.',
      compliance: 'Confirm compliance, inspections, reporting, and collections are covered.',
    },
    action: { label: 'Review Coverage', onclick: "focusCoverageArea('maintenance')" },
  },
  {
    day: 6,
    title: 'Set the weekly operating rhythm',
    base: 'Decide what gets reviewed daily, weekly, and monthly so the map stays alive.',
    focus: {
      stability: 'Create a daily gaps review and weekly owner update rhythm.',
      maintenance: 'Create a daily open-repair review and weekly vendor follow-up review.',
      growth: 'Create a weekly leasing pipeline and onboarding capacity review.',
      compliance: 'Create a weekly notices, inspections, and reporting review.',
    },
    action: { label: 'Open Tracking', onclick: "switchView('tracking', document.querySelector('.nav-tab'))" },
  },
  {
    day: 7,
    title: 'Export the operating manual',
    base: 'Download the handbook and launch plan, then review them with the team as the first SOP draft.',
    focus: {
      stability: 'Use the handbook as the team baseline before adding more process.',
      maintenance: 'Use the handbook to document escalation, vendor dispatch, and repair closeout.',
      growth: 'Use the handbook to document leasing-to-operations handoffs.',
      compliance: 'Use the handbook to document evidence, notices, and owner reporting expectations.',
    },
    action: { label: 'Download Handbook', onclick: 'downloadLaunchHandbook()' },
  },
];

export function renderLaunchPlan() {
  // Called by app init, ui.updateStats(), onboarding submit, checklist changes,
  // and guided action handlers. Keep this render idempotent and derived from
  // current state; do not mutate orgData/teamData/workOrders here.
  const container = document.getElementById('launch-plan');
  if (!container || !orgData) return;

  const profile = getOpsProfile();
  const focus = profile.focus || 'stability';
  const blueprint = FOCUS_BLUEPRINTS[focus] || FOCUS_BLUEPRINTS.stability;
  const checklist = getLaunchChecklist(focus);
  const saved = readChecklistState();
  const completeCount = checklist.filter(item => saved[item.id] || item.metric()).length;
  const gaps = getLaunchGaps();
  const nextAction = getNextAction();
  const readiness = getReadinessScore(checklist, saved);
  const snapshot = getOperationsSnapshot();
  const commandModules = getCommandModules(snapshot);
  const riskQueue = getRiskQueue(snapshot);
  const coverageAreas = getCriticalCoverageAreas();
  const dataQuality = getDataQualityChecks();
  const sevenDayPlan = getSevenDayPlan(profile);
  const blueprintDepts = blueprint.departments
    .map(id => orgData.departments.find(dept => dept.id === id))
    .filter(Boolean);

  container.innerHTML = `
    <div class="launch-dashboard-header">
      <div>
        <div class="launch-kicker">Beginner PM Command Center</div>
        <h3>${escapeHtml(getCompanyName())} operating snapshot</h3>
        <p>One place to set ownership, catch maintenance risk, build the team routine, and export the handbook before the company needs heavyweight software.</p>
      </div>
      <div class="launch-readiness-card" aria-label="${readiness.score} percent launch readiness">
        <strong>${readiness.score}%</strong>
        <span>${escapeHtml(readiness.label)}</span>
      </div>
    </div>
    <div class="launch-metrics-grid" aria-label="Launch readiness metrics">
      ${renderMetricCard('Portfolio', String(snapshot.propertyCount), `${snapshot.unitCount} units / ${snapshot.tenantCount} tenants / ${snapshot.vendorCount} vendors`, snapshot.propertyCount && snapshot.tenantCount && snapshot.vendorCount ? 'good' : 'warn')}
      ${renderMetricCard('Owned tasks', `${snapshot.assignedTasks}/${snapshot.totalTasks}`, `${snapshot.unownedTasks} unowned`, snapshot.unownedTasks ? 'warn' : 'good')}
      ${renderMetricCard('Team roster', String(snapshot.employeeCount), snapshot.isStarterTeam ? 'sample roster' : 'real people', snapshot.isStarterTeam ? 'warn' : 'good')}
      ${renderMetricCard('Open repairs', String(snapshot.openWorkOrders), `${snapshot.unassignedWorkOrders} unassigned`, snapshot.unassignedWorkOrders ? 'warn' : 'good')}
      ${renderMetricCard('Blocked work', String(snapshot.blockedTasks), `${snapshot.overdueTasks} overdue`, snapshot.blockedTasks || snapshot.overdueTasks ? 'danger' : 'good')}
    </div>
    <div class="launch-start">
      <div>
        <div class="launch-kicker">Start Here</div>
        <h3>${escapeHtml(nextAction.title)}</h3>
        <p>${escapeHtml(nextAction.detail)}</p>
      </div>
      <button class="btn btn-primary launch-primary-action" onclick="${nextAction.onclick}">
        ${escapeHtml(nextAction.button)}
      </button>
    </div>
    ${renderSetupWizard(snapshot)}
    <div class="launch-command-grid" aria-label="Beginner property manager modules">
      ${commandModules.map(renderCommandModule).join('')}
    </div>
    <div class="launch-coverage-panel" aria-label="Critical responsibility coverage">
      <div class="launch-coverage-head">
        <div>
          <div class="launch-kicker">Task Ownership Map</div>
          <h3>Critical PM coverage</h3>
          <p>These are the seven responsibility lanes a beginner property manager needs named before the work gets noisy.</p>
        </div>
        <div class="launch-coverage-score">
          <strong>${coverageAreas.filter(area => area.coveragePct === 100).length}/${coverageAreas.length}</strong>
          <span>fully covered</span>
        </div>
      </div>
      <div class="launch-coverage-grid">
        ${coverageAreas.map(renderCoverageArea).join('')}
      </div>
    </div>
    <div class="launch-risk-panel">
      <div>
        <div class="launch-kicker">Risk Queue</div>
        <h3>What needs attention before this can run cleanly?</h3>
      </div>
      <div class="launch-risk-list">
        ${riskQueue.length
          ? riskQueue.map(renderRiskItem).join('')
          : '<div class="launch-risk-empty">No major launch risks detected. Keep adding real properties, vendors, dates, and SOP detail as work comes in.</div>'
        }
      </div>
    </div>
    <div class="launch-quality-panel" aria-label="Data quality checks">
      <div class="launch-quality-head">
        <div>
          <div class="launch-kicker">Data Quality</div>
          <h3>Can this setup be trusted outside the app?</h3>
          <p>These checks look for incomplete records before a beginner exports CSVs, shares the handbook, or starts operating from the map.</p>
        </div>
        <div class="launch-quality-score">
          <strong>${dataQuality.passed}/${dataQuality.total}</strong>
          <span>checks clear</span>
        </div>
      </div>
      <div class="launch-quality-grid">
        ${dataQuality.checks.map(renderDataQualityCheck).join('')}
      </div>
    </div>
    <div class="launch-plan-header">
      <div>
        <div class="launch-kicker">Launch Plan</div>
        <h3>${escapeHtml(blueprint.title)}</h3>
        <p>${escapeHtml(blueprint.summary)}</p>
      </div>
      <div class="launch-score" aria-label="${completeCount} of ${checklist.length} launch steps complete">
        <strong>${completeCount}/${checklist.length}</strong>
        <span>ready steps</span>
      </div>
    </div>
    <div class="launch-week-panel" aria-label="First seven days launch plan">
      <div class="launch-week-head">
        <div>
          <div class="launch-kicker">First 7 Days</div>
          <h3>${escapeHtml(sevenDayPlan.heading)}</h3>
          <p>${escapeHtml(sevenDayPlan.summary)}</p>
        </div>
      </div>
      <div class="launch-week-grid">
        ${sevenDayPlan.days.map(renderSevenDayItem).join('')}
      </div>
    </div>
    <div class="launch-plan-grid">
      <div class="launch-panel">
        <div class="launch-panel-title">Recommended Blueprint</div>
        <div class="launch-profile-line">
          ${escapeHtml(PROFILE_LABELS[profile.portfolioSize] || PROFILE_LABELS.mid)} / ${escapeHtml(PROFILE_LABELS[focus] || PROFILE_LABELS.stability)}
        </div>
        <div class="launch-dept-list">
          ${blueprintDepts.map(dept => `
            <button class="launch-dept-pill" style="--dept-color:${dept.color}" onclick="focusLaunchDepartment('${dept.id}')">
              ${escapeHtml(dept.name)}
            </button>
          `).join('')}
        </div>
      </div>
      <div class="launch-panel">
        <div class="launch-panel-title">First-Week Checklist</div>
        <div class="launch-checklist">
          ${checklist.map(item => renderChecklistItem(item, saved[item.id])).join('')}
        </div>
      </div>
      <div class="launch-panel launch-gap-panel">
        <div class="launch-panel-title">Setup Gaps</div>
        ${gaps.length
          ? `<div class="launch-gap-list">${gaps.map(gap => `
              <div class="launch-gap">
                <strong>${escapeHtml(gap.title)}</strong>
                <span>${escapeHtml(gap.detail)}</span>
              </div>
            `).join('')}</div>`
          : '<p class="launch-empty">Core launch signals look good. Keep tightening owners, dates, and playbooks as the company grows.</p>'
        }
      </div>
    </div>
    <div class="launch-actions">
      <button class="btn btn-secondary" onclick="downloadLaunchPlan()">Download Launch Plan</button>
      <button class="btn btn-secondary" onclick="printLaunchPlan()">Print Launch Plan</button>
      <button class="btn btn-secondary" onclick="loadDemoCompany()">Load Demo Company</button>
      <button class="btn btn-secondary" onclick="resetLaunchChecklist()">Reset Checklist</button>
    </div>
  `;
}

export function toggleLaunchChecklistItem(id, checked) {
  const state = readChecklistState();
  state[id] = Boolean(checked);
  writeChecklistState(state);
  renderLaunchPlan();
}

export function resetLaunchChecklist() {
  try { localStorage.removeItem(LAUNCH_CHECKLIST_KEY); } catch (_) {}
  renderLaunchPlan();
}

export function startTeamSetup() {
  // Used by the generated Start Here button. app.js must expose this on window.
  switchToView('team', 'team-tab');
  document.getElementById('new-emp-name')?.focus();
}

export function showUnownedTasks() {
  // Depends on tracking.js exposing applyFilter on window through app.js.
  switchToView('tracking', document.querySelector('.nav-tab'));
  const ownerFilter = document.getElementById('owner-filter');
  if (ownerFilter) ownerFilter.value = 'UNOWNED';
  if (window.applyFilter) window.applyFilter();
  document.getElementById('departments')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

export function startWorkOrderSetup() {
  // Depends on workorders.js exposing showNewWorkOrderModal on window via app.js.
  switchToView('workorders', 'wo-tab');
  setTimeout(() => {
    if (window.showNewWorkOrderModal) window.showNewWorkOrderModal();
  }, 100);
}

export function downloadLaunchHandbook() {
  // Depends on handbook.js exposing downloadOperationsHandbook on window via app.js.
  if (window.downloadOperationsHandbook) window.downloadOperationsHandbook();
}

function _applyDemoCompanyData() {
  const demo = buildDemoWorkspace();
  const template = ROLE_TEMPLATES.maintenanceHeavy;
  const employees = template.employees.map(emp => ({
    name: emp.name,
    hex: emp.hex,
    affinities: [...emp.affinities],
  }));

  setTeamData({ employees });
  setPortfolio(demo.portfolio);
  setWorkOrders(demo.workOrders);
  applyDemoAssignments(employees);

  try {
    localStorage.setItem(COMPANY_KEY, demo.company);
    localStorage.setItem(OPS_PROFILE_KEY, JSON.stringify(demo.profile));
  } catch (_) {}
  applyCompanyName(demo.company);
  applyOpsProfile(demo.profile);
  saveTeamData();
  savePortfolio();
  saveWorkOrders();
  saveToStorage();
  logAudit('demo_company_loaded', { title: demo.company });
  renderLaunchPlan();
  if (window.renderTrackingView) window.renderTrackingView();
  if (window.populateOwnerFilter) window.populateOwnerFilter();
  if (window.renderLegend) window.renderLegend();
  if (window.updateStats) window.updateStats();
}

export function loadDemoCompany() {
  if (!confirm('Load the demo company?\n\nThis replaces local portfolio, team, work orders, company profile, and task assignments with a realistic sample workspace.')) return;
  _applyDemoCompanyData();
  _showActionToast('Demo company loaded', 'save-toast--success');
}

// Called from the onboarding modal's "Show me an example first" button — no
// confirmation dialog, since onboarding only ever runs on an empty workspace
// with nothing to lose.
export function startWithDemoCompany() {
  document.getElementById('onboarding-modal')?.classList.remove('visible');
  _applyDemoCompanyData();
  _showActionToast('Demo company loaded — explore it, then replace with your own data anytime', 'save-toast--success');
}

export function focusLaunchDepartment(deptId) {
  const deptEl = document.querySelector(`.department[data-id="${deptId}"]`);
  if (!deptEl) return;
  deptEl.style.display = '';
  deptEl.classList.add('expanded');
  deptEl.scrollIntoView({ behavior: 'smooth', block: 'start' });
  deptEl.classList.add('launch-highlight');
  setTimeout(() => deptEl.classList.remove('launch-highlight'), 1600);
}

export function downloadLaunchPlan() {
  const profile = getOpsProfile();
  const focus = profile.focus || 'stability';
  const blueprint = FOCUS_BLUEPRINTS[focus] || FOCUS_BLUEPRINTS.stability;
  const saved = readChecklistState();
  const checklist = getLaunchChecklist(focus);
  const gaps = getLaunchGaps();
  const coverage = getCriticalCoverageAreas();
  const sevenDayPlan = getSevenDayPlan(profile);
  const company = getCompanyName();
  const lines = [
    `# ${company} Launch Plan`,
    '',
    `Blueprint: ${blueprint.title}`,
    `Portfolio: ${PROFILE_LABELS[profile.portfolioSize] || PROFILE_LABELS.mid}`,
    `Focus: ${PROFILE_LABELS[focus] || PROFILE_LABELS.stability}`,
    '',
    '## First-Week Checklist',
    ...checklist.map(item => `- [${saved[item.id] || item.metric() ? 'x' : ' '}] ${item.label} - ${item.detail}`),
    '',
    '## First 7 Days',
    ...sevenDayPlan.days.map(item => `- Day ${item.day}: ${item.title} - ${item.detail}`),
    '',
    '## Critical Coverage',
    ...coverage.map(area => `- ${area.label}: ${area.coveragePct}% covered (${area.unownedCount} unowned / ${area.taskCount} tasks). Owners: ${area.primaryOwners}`),
    '',
    '## Setup Gaps',
    ...(gaps.length ? gaps.map(gap => `- ${gap.title}: ${gap.detail}`) : ['- No major setup gaps detected.']),
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${_slugify(company)}-launch-plan.md`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
  _showActionToast('Launch plan downloaded', 'save-toast--success');
}

export function printLaunchPlan() {
  const profile = getOpsProfile();
  const focus = profile.focus || 'stability';
  const blueprint = FOCUS_BLUEPRINTS[focus] || FOCUS_BLUEPRINTS.stability;
  const saved = readChecklistState();
  const checklist = getLaunchChecklist(focus);
  const coverage = getCriticalCoverageAreas();
  const gaps = getLaunchGaps();
  const html = `
    <html>
      <head>
        <title>${escapeHtml(getCompanyName())} Launch Plan</title>
        <style>
          body { font-family: Arial, sans-serif; color: #263238; padding: 28px; line-height: 1.45; }
          h1, h2 { margin-bottom: 6px; }
          section { break-inside: avoid; margin-bottom: 24px; }
          li { margin: 5px 0; }
          .muted { color: #607d8b; }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(getCompanyName())} Launch Plan</h1>
        <p class="muted">${escapeHtml(blueprint.title)} / ${escapeHtml(PROFILE_LABELS[focus] || PROFILE_LABELS.stability)}</p>
        <section><h2>Checklist</h2><ul>${checklist.map(item => `<li>${saved[item.id] || item.metric() ? '[x]' : '[ ]'} ${escapeHtml(item.label)} - ${escapeHtml(item.detail)}</li>`).join('')}</ul></section>
        <section><h2>Critical Coverage</h2><ul>${coverage.map(area => `<li>${escapeHtml(area.label)}: ${area.coveragePct}% covered, ${area.unownedCount} unowned. Owners: ${escapeHtml(area.primaryOwners)}</li>`).join('')}</ul></section>
        <section><h2>Setup Gaps</h2><ul>${(gaps.length ? gaps : [{ title: 'No major setup gaps detected', detail: 'Keep refreshing real data as work changes.' }]).map(gap => `<li>${escapeHtml(gap.title)}: ${escapeHtml(gap.detail)}</li>`).join('')}</ul></section>
      </body>
    </html>`;
  const win = window.open('', '_blank');
  if (!win) {
    alert('Popup blocked. Allow popups to print the launch plan.');
    return;
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

function renderChecklistItem(item, manuallyChecked) {
  const complete = manuallyChecked || item.metric();
  return `
    <label class="launch-check-item ${complete ? 'is-complete' : ''}">
      <input type="checkbox" ${complete ? 'checked' : ''} onchange="toggleLaunchChecklistItem('${item.id}', this.checked)">
      <span>
        <strong>${escapeHtml(item.label)}</strong>
        <small>${escapeHtml(item.detail)}</small>
      </span>
    </label>
  `;
}

function renderMetricCard(label, value, detail, tone) {
  return `
    <div class="launch-metric-card launch-metric-card--${tone}">
      <span>${escapeHtml(label)}</span>
      <strong>${escapeHtml(value)}</strong>
      <small>${escapeHtml(detail)}</small>
    </div>
  `;
}

function renderSetupWizard(snapshot) {
  const steps = [
    {
      label: 'Property',
      detail: 'Add what you manage.',
      done: snapshot.propertyCount > 0,
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      label: 'Tenant',
      detail: 'Attach resident context.',
      done: snapshot.tenantCount > 0,
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      label: 'Vendor',
      detail: 'Build the repair bench.',
      done: snapshot.vendorCount > 0,
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      label: 'Team',
      detail: 'Add your people.',
      done: snapshot.employeeCount > 0 && !snapshot.isStarterTeam,
      onclick: 'startTeamSetup()',
    },
    {
      label: 'First work order',
      detail: 'Test maintenance flow.',
      done: snapshot.workOrderCount > 0,
      onclick: 'startWorkOrderSetup()',
    },
  ];
  const complete = steps.filter(step => step.done).length;
  return `
    <div class="setup-wizard-panel" aria-label="Beginner setup wizard">
      <div class="setup-wizard-head">
        <div>
          <div class="launch-kicker">Setup Wizard</div>
          <h3>Property -> tenant -> vendor -> team -> first work order</h3>
          <p>Walk the first operating loop in order. Each step opens the exact place to complete it.</p>
        </div>
        <div class="setup-wizard-score"><strong>${complete}/${steps.length}</strong><span>complete</span></div>
      </div>
      <div class="setup-wizard-steps">
        ${steps.map((step, idx) => `
          <button class="setup-wizard-step ${step.done ? 'is-complete' : ''}" onclick="${step.onclick}">
            <span>${idx + 1}</span>
            <strong>${escapeHtml(step.label)}</strong>
            <small>${escapeHtml(step.detail)}</small>
          </button>
        `).join('')}
      </div>
    </div>
  `;
}

function renderCommandModule(module) {
  return `
    <div class="launch-command-card launch-command-card--${module.tone}">
      <div class="launch-command-top">
        <span class="launch-command-icon">${module.icon}</span>
        <span class="launch-command-status">${escapeHtml(module.status)}</span>
      </div>
      <strong>${escapeHtml(module.title)}</strong>
      <p>${escapeHtml(module.detail)}</p>
      <button class="btn btn-secondary launch-command-btn" onclick="${module.onclick}">
        ${escapeHtml(module.button)}
      </button>
    </div>
  `;
}

function renderRiskItem(risk) {
  return `
    <button class="launch-risk-item launch-risk-item--${risk.tone}" onclick="${risk.onclick}">
      <span>${escapeHtml(risk.label)}</span>
      <strong>${escapeHtml(risk.title)}</strong>
      <small>${escapeHtml(risk.detail)}</small>
    </button>
  `;
}

function renderCoverageArea(area) {
  const tone = area.coveragePct === 100 ? 'good' : area.coveragePct >= 70 ? 'warn' : 'danger';
  return `
    <button class="launch-coverage-card launch-coverage-card--${tone}" onclick="focusCoverageArea('${area.id}')">
      <span>${escapeHtml(area.label)}</span>
      <strong>${area.coveragePct}%</strong>
      <small>${area.unownedCount} unowned / ${area.taskCount} tasks</small>
      <em>${escapeHtml(area.primaryOwners)}</em>
    </button>
  `;
}

function renderSevenDayItem(item) {
  return `
    <article class="launch-day-card">
      <div class="launch-day-num">Day ${item.day}</div>
      <h4>${escapeHtml(item.title)}</h4>
      <p>${escapeHtml(item.detail)}</p>
      <button class="btn btn-secondary launch-day-action" onclick="${item.action.onclick}">
        ${escapeHtml(item.action.label)}
      </button>
    </article>
  `;
}

function renderDataQualityCheck(check) {
  return `
    <button class="launch-quality-card launch-quality-card--${check.tone}" onclick="${check.onclick}">
      <span>${escapeHtml(check.label)}</span>
      <strong>${escapeHtml(check.title)}</strong>
      <small>${escapeHtml(check.detail)}</small>
    </button>
  `;
}

function getLaunchChecklist(focus) {
  return [...BASE_CHECKLIST, ...(FOCUS_CHECKLIST[focus] || [])];
}

function getSevenDayPlan(profile) {
  const focus = profile.focus || 'stability';
  const portfolioSize = profile.portfolioSize || 'mid';
  const sizeGuidance = {
    small: 'Keep it lean: one owner per lane, one backup for maintenance and emergencies, and a simple weekly review.',
    mid: 'Balance coverage: identify primary owners, backup owners, and daily review points before volume spreads out.',
    large: 'Control handoffs early: split primary, backup, and escalation ownership before work crosses teams.',
  };

  return {
    heading: `${PROFILE_LABELS[portfolioSize] || PROFILE_LABELS.mid} / ${PROFILE_LABELS[focus] || PROFILE_LABELS.stability}`,
    summary: sizeGuidance[portfolioSize] || sizeGuidance.mid,
    days: SEVEN_DAY_PLAN.map(day => ({
      ...day,
      detail: day.focus[focus] || day.base,
    })),
  };
}

function applyDemoAssignments(employees) {
  const workload = new Map(employees.map(emp => [emp.name, 0]));
  orgData.departments.forEach(dept => {
    const candidates = employees.filter(emp => emp.affinities.includes(dept.id));
    const fallback = candidates.length ? candidates : employees;
    dept.tasks.forEach(task => {
      fallback.sort((a, b) => (workload.get(a.name) || 0) - (workload.get(b.name) || 0));
      const winner = fallback[0];
      task.owner = winner ? winner.name : 'UNOWNED';
      task.status = 'todo';
      task.priority = task.priority || 'medium';
      task.dueDate = null;
      task.blockedBy = null;
      if (winner) workload.set(winner.name, (workload.get(winner.name) || 0) + 1);
    });
  });
}

function getReadinessScore(checklist, saved) {
  const snapshot = getOperationsSnapshot();
  const dataQuality = getDataQualityChecks();
  const checklistComplete = checklist.filter(item => saved[item.id] || item.metric()).length / Math.max(checklist.length, 1);
  const ownershipScore = snapshot.totalTasks ? snapshot.assignedTasks / snapshot.totalTasks : 0;
  const teamScore = snapshot.employeeCount && !snapshot.isStarterTeam ? 1 : 0.35;
  const portfolioScore = (snapshot.propertyCount ? 0.42 : 0) + (snapshot.tenantCount ? 0.28 : 0) + (snapshot.vendorCount ? 0.3 : 0);
  const maintenanceScore = snapshot.workOrderCount
    ? Math.max(0.25, 1 - (snapshot.unassignedWorkOrders / Math.max(snapshot.openWorkOrders, 1)))
    : 0.25;
  const qualityScore = dataQuality.total ? dataQuality.passed / dataQuality.total : 1;
  const riskPenalty = Math.min(0.25, ((snapshot.blockedTasks + snapshot.overdueTasks) / Math.max(snapshot.totalTasks, 1)) * 2);
  const score = Math.max(0, Math.min(100, Math.round(
    ((ownershipScore * 0.28) + (teamScore * 0.18) + (portfolioScore * 0.15) + (maintenanceScore * 0.15) + (checklistComplete * 0.16) + (qualityScore * 0.08) - riskPenalty) * 100
  )));

  let label = 'Needs setup';
  if (score >= 85) label = 'Launch ready';
  else if (score >= 65) label = 'Operational';
  else if (score >= 40) label = 'Getting organized';

  return { score, label };
}

function getOperationsSnapshot() {
  const totalTasks = orgData.departments.reduce((sum, dept) => sum + dept.tasks.length, 0);
  const unownedTasks = countUnowned();
  const assignedTasks = totalTasks - unownedTasks;
  const blockedTasks = orgData.departments.reduce(
    (sum, dept) => sum + dept.tasks.filter(task => task.status === 'blocked').length,
    0
  );
  const todayISO = new Date().toISOString().slice(0, 10);
  const overdueTasks = orgData.departments.reduce(
    (sum, dept) => sum + dept.tasks.filter(task => task.dueDate && task.dueDate < todayISO && task.status !== 'done').length,
    0
  );
  const openWorkOrders = workOrders.filter(w => w.status !== 'completed').length;
  const unassignedWorkOrders = workOrders.filter(w => w.assignee === 'UNASSIGNED' && w.status !== 'completed').length;
  const leasesNeedingAttention = portfolio.tenants.filter(tenant => {
    const status = getLeaseStatus(tenant);
    return status && (status.tone === 'warn' || status.tone === 'danger');
  }).length;
  const delinquentTenants = portfolio.tenants.filter(tenant => getDelinquencyStatus(tenant)).length;
  const totalBalanceDue = portfolio.tenants.reduce((sum, tenant) => sum + Number(tenant.balanceDue || 0), 0);

  return {
    totalTasks,
    assignedTasks,
    unownedTasks,
    blockedTasks,
    overdueTasks,
    workOrderCount: workOrders.length,
    openWorkOrders,
    unassignedWorkOrders,
    propertyCount: portfolio.properties.length,
    unitCount: portfolio.properties.reduce((sum, property) => sum + Number(property.units || 0), 0),
    tenantCount: portfolio.tenants.length,
    vendorCount: portfolio.vendors.length,
    employeeCount: teamData.employees.length,
    isStarterTeam: isStarterTeam(),
    leasesNeedingAttention,
    delinquentTenants,
    totalBalanceDue,
  };
}

function getCriticalCoverageAreas() {
  return CRITICAL_COVERAGE_AREAS.map(area => {
    const depts = area.departments
      .map(id => orgData.departments.find(dept => dept.id === id))
      .filter(Boolean);
    const tasks = depts.flatMap(dept => dept.tasks);
    const unownedCount = tasks.filter(task => task.owner === 'UNOWNED').length;
    const ownerCounts = new Map();
    tasks.forEach(task => {
      if (task.owner !== 'UNOWNED') ownerCounts.set(task.owner, (ownerCounts.get(task.owner) || 0) + 1);
    });
    const primaryOwners = [...ownerCounts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([name]) => name)
      .join(', ') || 'No named owner';

    return {
      ...area,
      taskCount: tasks.length,
      unownedCount,
      primaryOwners,
      coveragePct: tasks.length ? Math.round(((tasks.length - unownedCount) / tasks.length) * 100) : 0,
    };
  });
}

function getCommandModules(snapshot) {
  return [
    {
      icon: '01',
      title: 'Portfolio Basics',
      status: snapshot.propertyCount ? `${snapshot.propertyCount} properties` : 'missing',
      tone: snapshot.propertyCount && snapshot.tenantCount && snapshot.vendorCount ? 'good' : 'warn',
      detail: 'Capture properties, unit counts, owner/client names, tenant roster, and starter vendor bench before daily work starts moving.',
      button: 'Open Portfolio',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      icon: '02',
      title: 'Ownership Map',
      status: snapshot.unownedTasks ? `${snapshot.unownedTasks} gaps` : 'ready',
      tone: snapshot.unownedTasks ? 'warn' : 'good',
      detail: 'Name who owns every recurring operating responsibility across leasing, maintenance, accounting, compliance, and owner updates.',
      button: snapshot.unownedTasks ? 'Close Gaps' : 'Review Map',
      onclick: snapshot.unownedTasks ? 'showUnownedTasks()' : "switchView('map', document.querySelector('[onclick*=map]'))",
    },
    {
      icon: '03',
      title: 'Team Operating Model',
      status: snapshot.isStarterTeam ? 'sample team' : `${snapshot.employeeCount} people`,
      tone: snapshot.isStarterTeam ? 'warn' : 'good',
      detail: 'Replace sample roles with real people, set department affinities, and spot overload before work becomes invisible.',
      button: 'Open Team',
      onclick: 'startTeamSetup()',
    },
    {
      icon: '04',
      title: 'Maintenance Flow',
      status: snapshot.workOrderCount ? `${snapshot.openWorkOrders} open` : 'not tested',
      tone: snapshot.unassignedWorkOrders || !snapshot.workOrderCount ? 'warn' : 'good',
      detail: 'Validate intake, dispatch, vendor, cost, due date, and closeout with at least one starter work order.',
      button: snapshot.workOrderCount ? 'Open Board' : 'Create First WO',
      onclick: snapshot.workOrderCount ? "switchView('workorders', document.getElementById('wo-tab'))" : 'startWorkOrderSetup()',
    },
    {
      icon: '05',
      title: 'SOP Handbook',
      status: snapshot.unownedTasks ? 'draft only' : 'exportable',
      tone: snapshot.unownedTasks ? 'neutral' : 'good',
      detail: 'Turn the live map into a Markdown starter handbook so new managers have a source of truth from day one.',
      button: 'Download SOP',
      onclick: 'downloadLaunchHandbook()',
    },
  ];
}

function getRiskQueue(snapshot) {
  const risks = [];
  const weakCoverage = getCriticalCoverageAreas().filter(area => area.coveragePct < 70);
  const failingQualityChecks = getDataQualityChecks().checks.filter(check => check.tone !== 'good');
  if (weakCoverage.length) {
    risks.push({
      label: 'Ownership Map',
      title: `${weakCoverage.length} critical coverage lane${weakCoverage.length === 1 ? '' : 's'} under 70%`,
      detail: `${weakCoverage.map(area => area.label).slice(0, 3).join(', ')} need clearer ownership.`,
      tone: 'danger',
      onclick: `focusCoverageArea('${weakCoverage[0].id}')`,
    });
  }
  if (!snapshot.propertyCount) {
    risks.push({
      label: 'Portfolio',
      title: 'No managed properties are recorded',
      detail: 'Add at least one property with units and owner/client context.',
      tone: 'warn',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (!snapshot.tenantCount) {
    risks.push({
      label: 'Tenants',
      title: 'No tenant roster exists yet',
      detail: 'Add at least one tenant so maintenance and communication have unit-level context.',
      tone: 'warn',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (!snapshot.vendorCount) {
    risks.push({
      label: 'Vendors',
      title: 'No starter vendor bench exists',
      detail: 'Add at least one vendor before the first urgent repair hits.',
      tone: 'warn',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (snapshot.leasesNeedingAttention > 0) {
    risks.push({
      label: 'Leases',
      title: `${snapshot.leasesNeedingAttention} lease${snapshot.leasesNeedingAttention === 1 ? '' : 's'} expired or renewing within 60 days`,
      detail: 'Reach out about renewal or move-out before the lease end date arrives.',
      tone: 'danger',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (snapshot.delinquentTenants > 0) {
    risks.push({
      label: 'Delinquency',
      title: `${snapshot.delinquentTenants} tenant${snapshot.delinquentTenants === 1 ? '' : 's'} behind on rent — ${formatCurrency(snapshot.totalBalanceDue)} outstanding`,
      detail: 'Follow up before balances grow past a full month behind.',
      tone: 'danger',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (snapshot.isStarterTeam) {
    risks.push({
      label: 'Team',
      title: 'Sample people are still assigned',
      detail: 'Replace starter owners with your real team before trusting the map.',
      tone: 'warn',
      onclick: 'startTeamSetup()',
    });
  }
  if (snapshot.unownedTasks > 0) {
    risks.push({
      label: 'Ownership',
      title: `${snapshot.unownedTasks} responsibilities have no owner`,
      detail: 'These are the highest-value gaps to close for a beginner PM company.',
      tone: 'danger',
      onclick: 'showUnownedTasks()',
    });
  }
  if (!snapshot.workOrderCount) {
    risks.push({
      label: 'Maintenance',
      title: 'Maintenance workflow has not been tested',
      detail: 'Create one realistic work order to prove intake, assignment, vendor, cost, and closeout.',
      tone: 'warn',
      onclick: 'startWorkOrderSetup()',
    });
  } else if (snapshot.unassignedWorkOrders > 0) {
    risks.push({
      label: 'Maintenance',
      title: `${snapshot.unassignedWorkOrders} open work orders are unassigned`,
      detail: 'Every repair needs a named accountable person.',
      tone: 'danger',
      onclick: "switchView('workorders', document.getElementById('wo-tab'))",
    });
  }
  if (snapshot.blockedTasks || snapshot.overdueTasks) {
    risks.push({
      label: 'Execution',
      title: `${snapshot.blockedTasks} blocked / ${snapshot.overdueTasks} overdue tasks`,
      detail: 'Review blocked or late responsibilities before the operating map becomes stale.',
      tone: 'danger',
      onclick: "switchView('tracking', document.querySelector('.nav-tab'))",
    });
  }
  if (failingQualityChecks.length) {
    risks.push({
      label: 'Data Quality',
      title: `${failingQualityChecks.length} setup data check${failingQualityChecks.length === 1 ? '' : 's'} need cleanup`,
      detail: `${failingQualityChecks[0].label}: ${failingQualityChecks[0].detail}`,
      tone: 'warn',
      onclick: failingQualityChecks[0].onclick,
    });
  }
  return risks.slice(0, 4);
}

function getNextAction() {
  // Beginner guidance engine. Order is intentional:
  // define portfolio -> personalize sample roster -> close UNOWNED task gaps ->
  // create maintenance workflow -> export handbook. Changing this order changes first-run UX.
  const unowned = countUnowned();
  const openUnassignedWorkOrders = workOrders.filter(w => w.assignee === 'UNASSIGNED' && w.status !== 'completed').length;

  if (!portfolio.properties.length || !portfolio.tenants.length || !portfolio.vendors.length) {
    return {
      title: 'Add your first property, tenant, and vendor',
      detail: 'Start by recording what you manage, who lives there, and who you can call for repairs. This makes the rest of the operating map feel real.',
      button: 'Open Portfolio',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    };
  }

  if (!teamData.employees.length || isStarterTeam()) {
    return {
      title: 'Add your real team first',
      detail: 'Every task starts unowned. Add your people so every responsibility can point to a real person.',
      button: 'Open Team Manager',
      onclick: 'startTeamSetup()',
    };
  }

  if (unowned > 0) {
    return {
      title: `Assign ${unowned} unowned responsibilities`,
      detail: 'Red UNOWNED items are the highest-priority setup gaps. Click each owner badge or use Auto-Assign after your team affinities look right.',
      button: 'Show Unowned Tasks',
      onclick: 'showUnownedTasks()',
    };
  }

  if (!workOrders.length || openUnassignedWorkOrders > 0) {
    return {
      title: 'Create a starter work order',
      detail: 'Use one sample repair to confirm intake, assignment, vendor, cost, target date, and closeout before real maintenance work arrives.',
      button: 'Create Work Order',
      onclick: 'startWorkOrderSetup()',
    };
  }

  return {
    title: 'Download your operations handbook',
    detail: 'Your core setup signals look good. Export the handbook so the team has a simple SOP starter pack to review and improve.',
    button: 'Download Handbook',
    onclick: 'downloadLaunchHandbook()',
  };
}

function switchToView(view, tabRef) {
  const tabEl = typeof tabRef === 'string' ? document.getElementById(tabRef) : tabRef;
  if (window.switchView && tabEl) window.switchView(view, tabEl);
}

export function focusCoverageArea(areaId) {
  const area = CRITICAL_COVERAGE_AREAS.find(item => item.id === areaId);
  if (!area) return;
  switchToView('tracking', document.querySelector('.nav-tab'));
  area.departments.forEach(deptId => {
    const deptEl = document.querySelector(`.department[data-id="${deptId}"]`);
    if (!deptEl) return;
    deptEl.style.display = '';
    deptEl.classList.add('expanded', 'launch-highlight');
    setTimeout(() => deptEl.classList.remove('launch-highlight'), 1600);
  });
  const firstDept = area.departments
    .map(deptId => document.querySelector(`.department[data-id="${deptId}"]`))
    .find(Boolean);
  firstDept?.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

function isStarterTeam() {
  // config.json ships with no starter names (ownerColors only defines UNOWNED),
  // so this only matches if a future config reintroduces named sample owners.
  if (!ownerColors || !teamData.employees.length) return false;
  const starterNames = Object.keys(ownerColors)
    .filter(name => name !== 'UNOWNED')
    .sort();
  const currentNames = teamData.employees.map(emp => emp.name).sort();
  if (starterNames.length !== currentNames.length) return false;
  return starterNames.every((name, idx) => currentNames[idx] === name);
}

function readChecklistState() {
  try {
    return JSON.parse(localStorage.getItem(LAUNCH_CHECKLIST_KEY)) || {};
  } catch (_) {
    return {};
  }
}

function writeChecklistState(state) {
  try { localStorage.setItem(LAUNCH_CHECKLIST_KEY, JSON.stringify(state)); } catch (_) {}
}

function hasAssignedDepartment(deptId) {
  const dept = orgData.departments.find(d => d.id === deptId);
  return Boolean(dept && dept.tasks.some(task => task.owner !== 'UNOWNED'));
}

function hasAnyWorkOrderSignal() {
  return workOrders.length > 0 || hasAssignedDepartment('maintenance');
}

function getOverloadedOwners() {
  if (!teamData.employees.length || !orgData) return [];
  const counts = new Map(teamData.employees.map(emp => [emp.name, 0]));
  orgData.departments.forEach(dept => {
    dept.tasks.forEach(task => {
      if (counts.has(task.owner)) counts.set(task.owner, counts.get(task.owner) + 1);
    });
  });
  const totalAssigned = [...counts.values()].reduce((sum, count) => sum + count, 0);
  const average = totalAssigned / Math.max(counts.size, 1);
  return [...counts.entries()]
    .filter(([, count]) => count > Math.max(35, average * 1.8))
    .map(([name]) => name);
}

function getDataQualityChecks() {
  const propertiesMissingOwner = portfolio.properties.filter(property => !(property.owner || '').trim()).length;
  const propertiesMissingUnits = portfolio.properties.filter(property => Number(property.units || 0) <= 0).length;
  const tenantsMissingContext = portfolio.tenants.filter(tenant =>
    !tenant.propertyId || !(tenant.unit || '').trim()
  ).length;
  const tenantsMissingContact = portfolio.tenants.filter(tenant =>
    !(tenant.phone || '').trim() && !(tenant.email || '').trim()
  ).length;
  const vendorsMissingContext = portfolio.vendors.filter(vendor =>
    !(vendor.trade || '').trim() || (!(vendor.phone || '').trim() && !(vendor.email || '').trim())
  ).length;
  const openWorkOrders = workOrders.filter(wo => wo.status !== 'completed');
  const openWorkOrdersMissingDetail = openWorkOrders.filter(wo =>
    wo.assignee === 'UNASSIGNED' || !(wo.vendor || '').trim() || !wo.dueDate || !(wo.property || '').trim()
  ).length;

  const checks = [
    {
      label: 'Properties',
      title: propertiesMissingOwner || propertiesMissingUnits ? 'Property records need detail' : 'Property records look usable',
      detail: propertiesMissingOwner || propertiesMissingUnits
        ? `${propertiesMissingOwner} missing owner/client, ${propertiesMissingUnits} missing unit count.`
        : 'Every property has owner/client context and a unit count.',
      tone: propertiesMissingOwner || propertiesMissingUnits ? 'warn' : 'good',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      label: 'Tenants',
      title: tenantsMissingContext || tenantsMissingContact ? 'Tenant roster needs cleanup' : 'Tenant roster is export-ready',
      detail: tenantsMissingContext || tenantsMissingContact
        ? `${tenantsMissingContext} missing property/unit, ${tenantsMissingContact} missing contact info.`
        : 'Every tenant has property, unit, and at least one contact method.',
      tone: tenantsMissingContext || tenantsMissingContact ? 'warn' : 'good',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      label: 'Vendors',
      title: vendorsMissingContext ? 'Vendor bench needs contact detail' : 'Vendor bench is dispatch-ready',
      detail: vendorsMissingContext
        ? `${vendorsMissingContext} vendor${vendorsMissingContext === 1 ? '' : 's'} missing trade or contact info.`
        : 'Every vendor has a trade and at least one contact method.',
      tone: vendorsMissingContext ? 'warn' : 'good',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      label: 'Work Orders',
      title: openWorkOrdersMissingDetail ? 'Open repairs need operating detail' : 'Open repairs are trackable',
      detail: openWorkOrdersMissingDetail
        ? `${openWorkOrdersMissingDetail} open work order${openWorkOrdersMissingDetail === 1 ? '' : 's'} missing owner, vendor, target date, or property.`
        : 'Every open repair has enough detail for follow-up.',
      tone: openWorkOrdersMissingDetail ? 'danger' : 'good',
      onclick: "switchView('workorders', document.getElementById('wo-tab'))",
    },
  ];

  return {
    checks,
    total: checks.length,
    passed: checks.filter(check => check.tone === 'good').length,
  };
}

function getLaunchGaps() {
  const gaps = [];
  const unowned = countUnowned();
  const overloaded = getOverloadedOwners();
  const unassignedWorkOrders = workOrders.filter(w => w.assignee === 'UNASSIGNED' && w.status !== 'completed').length;
  const qualityIssues = getDataQualityChecks().checks.filter(check => check.tone !== 'good');

  if (unowned > 0) {
    gaps.push({
      title: `${unowned} unowned responsibilities`,
      detail: 'Assign these before using the map as the operating source of truth.',
    });
  }
  if (!teamData.employees.length) {
    gaps.push({
      title: 'No team roster',
      detail: 'Add the first employees in Team Manager so responsibilities have real owners.',
    });
  }
  if (unassignedWorkOrders > 0) {
    gaps.push({
      title: `${unassignedWorkOrders} unassigned open work order${unassignedWorkOrders === 1 ? '' : 's'}`,
      detail: 'Assign each open job so maintenance does not become invisible work.',
    });
  }
  if (!workOrders.length) {
    gaps.push({
      title: 'No sample maintenance workflow',
      detail: 'Create one starter work order to validate intake, assignment, vendor, and closeout steps.',
    });
  }
  if (overloaded.length > 0) {
    gaps.push({
      title: 'Potential role overload',
      detail: `${overloaded.slice(0, 3).join(', ')} may need backup coverage or reassignment.`,
    });
  }
  if (qualityIssues.length > 0) {
    gaps.push({
      title: 'Incomplete setup records',
      detail: `${qualityIssues.map(check => check.label).slice(0, 3).join(', ')} need cleanup before export or handoff.`,
    });
  }

  return gaps.slice(0, 5);
}
